title: Ajay Dhandhukiya # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Frontend Engineer
  <br><br>
  <a href="mailto:ajaydhandhukiya.prajapati@gmail.com">ajaydhandhukiya.prajapati@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/ajay-dhandhukiya-a9b28a95/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/ajaydhandhukiya/">Gihub</a> 
theme: jekyll-theme-minimal
